#! /bin/sh

if [ $GDMSESSION = "awesome" ]
then
    sxhkd -c ~/.config/sxhkd/awesome_sxhkdrc \
             ~/.config/sxhkd/sxhkdrc
elif [ $GDMSESSION = "bspwm" ]
    sxhkd -c ~/.config/sxhkd/bspwm_sxhkdrc \
             ~/.config/sxhkd/sxhkdrc
elif [ $GDMSESSION = "dwm" ]
    sxhkd -c ~/.config/sxhkd/dwm_sxhkdrc \
             ~/.config/sxhkd/sxhkdrc
fi

fix &
