#!/bin/sh
export PATH="${PATH}:$HOME/bin"
export EDITOR=nvim
export TERMINAL=st

# starting backround programs
fix.sh &
#picom --experimental-backend &
unclutter &

# making a new pane to get access to universal clipboard
tmux attach-session -t freetime <<EOF
# Split the pane
split-window -h

# Close the first pane
kill-pane -t 0

# Detach from the session
detach-client
EOF
