#! /bin/sh
conf="bspc config"
rule="bspc rule"
export PATH="${PATH}:$HOME/bin"

# checking monitor count to see which layout to use
export MONITOR_NUM=$(xrandr | grep connected | grep -v disconnected | wc -l)

bspc monitor -d 1 2 3

$conf pointer_modifier		mod4
$conf pointer_action1		move
$conf pointer_action2		resize_corner
$conf focused_border_color	"#05E3E3"
$conf border_width		5
$conf window_gap		40

$conf split_ratio		0.50
$conf presel_feedback		false
$conf borderless_monocle	true
$conf gapless_monocle		true

#$rule -a mpv desktop=^4 follow=off
$rule -a spotify desktop=^2 follow=on
$rule -a mpv desktop=^2 follow=off
$rule -a sysinfo state=floating rectangle=310x350+800+30
$rule -a calinfo state=floating rectangle=300x250+800+30
$rule -a calcurse state=floating rectangle=600x600+630+30

fix &
sxhkd &
